version: '3'

services:
  magic:
    container_name: magic
    image: mage_spark 
    command: mage start ETL
    env_file:
      - Environment.env
    environment:
      USER_CODE_PATH: /home/src/ETL/
      ENV: ${ENV}
      SPARK_MASTER_HOST: 'local'  # Add this environment variable
    ports:
      - "6789:6789"
    volumes:
      - ".:/home/src"
    restart: on-failure:5
    build:
      context: .
      dockerfile: Dockerfile

  pgServer:
    container_name: pgServer
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - "postgres-data:/var/lib/postgresql/data"

  pgAdmin:
    container_name: pgAdmin
    image: dpage/pgadmin4
    depends_on:
      - pgServer
    environment:
      - PGADMIN_DEFAULT_EMAIL=mo7amed7assan1911@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8080:80"
    volumes:
      - "pgadmin-data:/var/lib/pgadmin"

volumes:
  postgres-data:
  pgadmin-data:
